// This file is generated by ttrpc-compiler 0.6.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct IoProxyClient {
    client: ::ttrpc::r#async::Client,
}

impl IoProxyClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        IoProxyClient {
            client: client,
        }
    }

    pub async fn state(&self, ctx: ttrpc::context::Context, req: &super::ioproxy::StateRequest) -> ::ttrpc::Result<super::ioproxy::StateResponse> {
        let mut cres = super::ioproxy::StateResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "fc_ctrd.IoProxy", "State", cres);
    }

    pub async fn attach(&self, ctx: ttrpc::context::Context, req: &super::ioproxy::AttachRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "fc_ctrd.IoProxy", "Attach", cres);
    }
}

struct StateMethod {
    service: Arc<Box<dyn IoProxy + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StateMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, ioproxy, StateRequest, state);
    }
}

struct AttachMethod {
    service: Arc<Box<dyn IoProxy + Send + Sync>>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AttachMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, ioproxy, AttachRequest, attach);
    }
}

#[async_trait]
pub trait IoProxy: Sync {
    async fn state(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::ioproxy::StateRequest) -> ::ttrpc::Result<super::ioproxy::StateResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/fc_ctrd.IoProxy/State is not supported".to_string())))
    }
    async fn attach(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::ioproxy::AttachRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/fc_ctrd.IoProxy/Attach is not supported".to_string())))
    }
}

pub fn create_io_proxy(service: Arc<Box<dyn IoProxy + Send + Sync>>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("State".to_string(),
                    Box::new(StateMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Attach".to_string(),
                    Box::new(AttachMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("fc_ctrd.IoProxy".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
